spring:
  profiles:
    active: ${active_profile}
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher