version: '3.9'
networks:
  test-network:
    name: test-network
    driver: bridge
services:
#  db:
#    image: mysql
#    container_name: mysqldb
#    restart: always
#    networks:
#      - test-network
#    environment:
#      # So you don't have to use root, but you can if you like
#      # You can use whatever password you like
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=123456
#      # Password for root access
#      - MYSQL_ROOT_PASSWORD=123456
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '3306:3306'
#    expose:
#      # Opens port 3306 on the container
#      - '3306:3306'
#      # Where our data will be persisted
#    volumes:
#      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
  backend:
    restart: always
    environment:
      active_profile: ${active_profile}
      datasource_url: ${datasource_url}
      datasource_username: ${datasource_username}
      datasource_password: ${datasource_password}
      mail_username: ${mail_username}
      mail_password: ${mail_password}
      hibernate_ddl_auto: update
    container_name: infrasave-backend
    build: ./infrasave-rest-app/
    image: mhnaydin/infrasave-backend
    ports:
      - '8080:8080'
    expose:
      - '8080:8080'
    networks:
      - test-network
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: '1'
  #          memory: 2000M
  #        reservations:
  #          cpus: '0.5'
  #          memory: 1000M
  frontend:
    restart: always
    container_name: infrasave-frontend
    build:
      context: ./infrasave-react-client
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    image: mhnaydin/infrasave-frontend
    ports:
      - '3000:80'
    expose:
      - '3000:80'
    networks:
      - test-network
#    deploy:
#      resources:
#        limits:
#          cpus: '1'ss
#          memory: 2000M
#        reservations:
#          cpus: '0.5'
#          memory: 1000M