version: '3.9'
networks:
  test-network:
    name: test-network
    driver: bridge
services:
  db:
    image: mysql
    container_name: mysqldb
    restart: always
    networks:
      - test-network
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=
      # Password for root access
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
  backend:
    restart: always
    environment:
      - active_profile=dev
      - datasource_url=jdbc:mysql://mysqldb:3306/infrasave
      - datasource_username=root
      - datasource_password=
      - hibernate_ddl_auto=update
    container_name: infrasave-backend
    build: ./infrasave-rest-app/
    image: mhnaydin/infrasave-backend
    ports:
      - '8080:8080'
    expose:
      - '8080:8080'
    networks:
      - test-network
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: '1'
  #          memory: 2000M
  #        reservations:
  #          cpus: '0.5'
  #          memory: 1000M
  frontend:
    restart: always
    container_name: infrasave-frontend
    build: ./infrasave-react-client
    image: mhnaydin/infrasave-frontend
    ports:
      - '80:3000'
    expose:
      - '80:3000'
    networks:
      - test-network
#    deploy:
#      resources:
#        limits:
#          cpus: '1'ss
#          memory: 2000M
#        reservations:
#          cpus: '0.5'
#          memory: 1000M